#Graphs for SDI univariate 



```{r}
# load in necessary libraries 
library(ggplot2)
#library(geojsonio)
library(ggthemes)
library(dplyr)
library(ggrepel)
library(scales)

```


```{r}
#load in our data
github_Link <-"https://raw.githubusercontent.com/EvanLih/PUBPOL-543-BEES-Project/master/Final_Data.csv"
finalData <- read.csv(github_Link)

```


```{r}
# SDI compared to Resource Rent (multivariate)
sdiResourceRent <- finalData %>% select(c("Continent", "ResourceRent", "Sustainable.Development.Index", "Country"))
sdiData = as.data.frame(sdiResourceRent)

##Evan CODE - this line of code "completecases" only keeps rows where there are outputs/non-missing values for specified columns. In this case, we are specifying all columns. 
sdiResourceRent <- sdiResourceRent[complete.cases(sdiResourceRent), ]
ggplot(sdiResourceRent, aes(y = ResourceRent, x = Sustainable.Development.Index, color=Continent)) +
  geom_point() +
  # geom_text_repel(aes(label = Country), size = 1) +
  labs(y = "Resource Rent", 
       x = "Sustainable Development Index", title="Continental Resource Rent by SDI") +
  theme_stata() + theme(legend.title=element_text(size=11))

#
#
# NOTE: NEED TO GET RID OF EMPTY CONTINENT RED DOT? HOW? Something to do with extra "X" variables??
#
#

```


```{r}
#SDI alone
ContinentSdi = aggregate(sdiResourceRent[, 3], list(sdiResourceRent$Continent), mean)

#ContinentSdi

ggplot(ContinentSdi, aes(x=reorder(Group.1, x), y= x)) + geom_bar(position="dodge", stat="identity") + labs(x="Continent", y="Average Sustainable Development Index", title="Sustainable Development Index by Continent") + theme_stata() + geom_text(aes(label=round(x, digits=2)), position=position_dodge(width=0.9), vjust=1.3, size=3.5, color="white") + theme(axis.text.x = element_text(angle=45, hjust=1, vjust=1, size=8)) + theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))) 
       
#
#
# NOTE: AGAIN, EXTRA CONTINENT??
# Also change colors??
#
#
#

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


