Load Packages:
```{r}
require(sf)
require(rgdal)
require(ggplot2)
require(readxl)
library(dplyr)
library(geojsonio)
library(magrittr)
library(ggrepel)
library(ggpmisc)
library(ggthemes)
```

Import Data:
```{r}
#Setting working directory to local folder
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

#Importaing our Dataset
github_Link <-"https://raw.githubusercontent.com/EvanLih/PUBPOL-543-BEES-Project/master/Final_Data.csv"
finalData <- read.csv(github_Link)
finalData = finalData[-c(161:999),]
```

```{r}
#Renaming the column "country" to COUNTRY  
finalData <- rename(finalData, COUNTRY = Country)
```

Subset to only have the variables of Renewable consumption, SDI, Continent and Country for analysis：
```{r}
#subset
RenewableConsumptionSet <- finalData %>% select(c("Continent", "RenewConsumption", "Sustainable.Development.Index", "COUNTRY"))

RenewableConsumptionSet$RenewConsumption %<>% as.numeric()

RenewableConsumptionSet %<>% rename(SDI = "Sustainable.Development.Index", country = "COUNTRY", RenewableConsumption = "RenewConsumption")

RenewableConsumptionSet %<>% filter(!is.na(RenewableConsumption))
```


Run a T-test to see the correlation between Renewable Consumption and SDI:
```{r}
#t.test to see correlation between access Electricity and SDI
t.test(x =RenewableConsumptionSet$RenewableConsumption, y = RenewableConsumptionSet$SDI,  paired = FALSE)
m <- lm(RenewableConsumptionSet$RenewableConsumption ~ RenewableConsumptionSet$SDI)
summary(m)$r.squared
```

Start to plot Renewable Comsumption and SDI:
```{r}
ggplot(RenewableConsumptionSet, aes(x = RenewableConsumption, y = SDI, 
                                    color=Continent)
       ) +
  geom_point() +
  #geom_text_repel(aes(label = country), size = 1.5) +
  labs(title = "How Renewable Energy Consumption and SDI Related?", x = "Renewable Energy Consumption (% of total energy consumption)", 
       y = "Sustainable Development Index", caption="Sources: Sustainable Development Project and The World Bank (2015)") +
  theme_stata() #+theme(legend.title=element_text(size=11))
```






Note for Evan: Stop from here ：）
```{r}
RenewableConsumptionSet1 <- RenewableConsumptionSet %>%
  filter(!is.na(RenewableConsumption)) %>%
  group_by(Continent) %>%
  summarise(meanConsumption = mean(RenewableConsumption), 
            meanSDI = mean(SDI))

```

```{r}
ggplot(RenewableConsumptionSet1, aes(x = meanConsumption, y = meanSDI)) +
  geom_text_repel(aes(label = Continent)) +
  geom_point() +
  labs(title = "Mean Consumption of Renewable Energy within Continents & SDI", x = "Renewable Energy Consumption (% of total energy consumption)", y = "Sustainability Development Index Rating (Mean)")+
  theme_stata()
```
```{r}
st_geometry(mapMerge) <- mapMerge$geometry

#Now we will create the plot. We call on the data from worldmap and its "simple feature" geom. Over that, we will overaly the data from "mapMerge" onto this plot. 
ggplot(data=worldMap) + 
  geom_sf() +
  geom_sf(data = mapMerge, aes(fill=`Sustainable Development Index`),color=NA,show.legend = T) +
  theme_map()
```
```{r}
RenewableConsumptionSet$RenewableCut=cut(RenewableConsumptionSet$RenewableConsumption,
                          breaks = c(0,25,50,75,100),
                          labels = c("less25","25-50","50-75","75-100"))
```
```{r}
absoluteT=table(RenewableConsumptionSet$RenewableCut)
absoluteT
```

```{r}
tableFreq=as.data.frame(absoluteT)
tableFreq
```
```{r}
names(tableFreq)=c("RenewableConsumptionPercentage","Count")
tableFreq
```
```{r}
ggplot(data = tableFreq, 
             aes(x = RenewableConsumptionPercentage,
                 y = Count)) + geom_bar(fill ="gray",
                        stat = 'identity') +
labs( title = "Renewable Consumption", x= "Renewable Energy Consumption (% of total energy consumption)" , y= "Number of Countries") +
theme_stata()
```

